export const soMainStyles = {
    layout: '!h-screen !flex !justify-center !bg-gradient-to-r from-[#00c4cc] via-[#6366f1] to-[#8b3dff]',
    layoutContainer: '!w-full !relative !mx-auto !h-full',
    fixedContainer: '!fixed !top-0 !left-0 !right-0 !flex !justify-center !z-50',
    fixedContent: '!w-full !relative',
    sider: '!absolute !left-10 !top-10 !bottom-10 !z-50 !rounded-xl !shadow-lg !bg-white !backdrop-blur-lg !h-[calc(100vh-80px)]',
    siderHeader: 'p-4 border-b border-gray-200',
    siderLogo: 'text-2xl font-bold',
    siderMenu: 'py-4',
    siderMenuItem: 'px-4 py-2 text-base font-medium hover:bg-gray-100 transition-colors cursor-pointer',
    innerLayout: '!h-full !bg-transparent',
    header: '!bg-transparent !py-3 !px-6 !flex !items-center !justify-end',
    // header: '!rounded-xl !shadow-lg !absolute !top-10 !left-80 !right-10 !z-50 !bg-white !backdrop-blur-lg !border-b !border-white !px-6 !flex !items-center !justify-between',
    headerTitle: 'text-2xl font-medium text-gray-800',
    headerIcons: 'flex items-center space-x-6',
    headerIcon: 'text-2xl text-gray-700 hover:text-[#00c4cc] transition-colors cursor-pointer',
    content: '!mt-[10px] !ml-[320px] !mr-[10px] !flex-1 !overflow-auto bg-white rounded-t-xl shadow-lg !h-[calc(100vh-100px)]',
}
