export const soMainStyles = {
    layout: '!h-screen !flex !justify-center !bg-gradient-to-r from-[#00c4cc]/5 via-[#6366f1]/80 to-[#8b3dff]/80 backdrop-blur-sm font-["Nunito"]',
    layoutContainer: '!w-full !relative !mx-auto !h-full',
    sider: 'px-4 py-2 !bg-transparent !h-full',
    siderHeader: 'pt-3 flex items-center justify-between',
    siderHeaderSmall: 'pt-3 flex items-center justify-center',
    siderLogo: 'text-2xl font-bold',
    siderMenu: 'py-4 flex flex-col gap-2',
    siderMenuItem:
        'flex items-center h-10 px-4 py-2 text-base font-medium cursor-pointer hover:bg-[#6366f1]/10 transition-all duration-100 ease-in-out rounded-lg text-[#6366f1] hover:text-[#4f46e5]',
    menuItemSelected: 'bg-[#6366f1]/10',
    siderCreateButton: '!w-full !py-6 !bg-[#6366f1] hover:!bg-[#4f46e5] !text-white !rounded-lg !font-medium !shadow-md !hover:!shadow-lg',
    siderCollapseButton: '!bg-transparent !border-none !shadow-none',
    sliderIcon: 'text-lg text-[#8b3dff]',
    sliderCollapseButtonText: 'ml-3 overflow-hidden whitespace-nowrap',
    innerLayout: '!h-full !bg-transparent',
    header: '!bg-transparent !py-2 !px-6 !flex !items-center !justify-end',
    headerTitle: 'text-2xl font-medium text-gray-800',
    headerIcons: 'flex items-center space-x-6',
    headerIcon: 'text-2xl text-gray-700 hover:text-[#00c4cc] transition-colors cursor-pointer',
    content: '!mt-[10px] !mr-[10px] !flex-1 !overflow-auto bg-white rounded-t-xl shadow-lg border border-gray-100 !h-[calc(100vh-100px)]',
    contentWrapper: 'h-full overflow-auto',
}
