export const soMainStyles = {
    layout: '!min-h-[1080px] !flex !justify-center !bg-gradient-to-r from-[#00c4cc] via-[#6366f1] to-[#8b3dff]',
    layoutContainer: '!w-full !max-w-[1920px] !min-w-[1280px] !relative !mx-auto',
    fixedContainer: '!fixed !top-0 !left-0 !right-0 !flex !justify-center !z-50',
    fixedContent: '!w-full !max-w-[1920px] !min-w-[1280px] !relative',
    sider: '!absolute !left-10 !top-10 !bottom-10 !z-50 !rounded-xl !shadow-lg !bg-white !backdrop-blur-lg !h-[calc(100vh-80px)]',
    siderHeader: 'p-4 border-b border-gray-200',
    siderLogo: 'text-2xl font-bold',
    siderMenu: 'py-4',
    siderMenuItem: 'px-4 py-2 text-base font-medium hover:bg-gray-100 transition-colors cursor-pointer',
    innerLayout: '!min-h-[1080px] !bg-transparent',
    header: '!rounded-xl !shadow-lg !absolute !top-10 !left-80 !right-10 !z-50 !bg-white !backdrop-blur-lg !border-b !border-white !px-6 !flex !items-center !justify-between',
    headerTitle: 'text-2xl font-medium text-gray-800',
    headerIcons: 'flex items-center space-x-6',
    headerIcon: 'text-2xl text-gray-700 hover:text-[#00c4cc] transition-colors cursor-pointer',
    content: '!mt-[130px] !ml-[320px] !mr-[40px] !mb-[40px] !flex-1 !overflow-auto !min-h-[calc(100vh-170px)] bg-white rounded-xl shadow-lg',
}
