export const estimateMenuStyles = {
    contentContainer: 'bg-white/4 backdrop-blur-lg p-8',
    contentTitle: 'text-3xl font-bold text-white mb-6',
    contentGrid: 'grid grid-cols-1 gap-6',
    newEstimateCard: 'bg-white/7 p-8 rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 cursor-pointer transform hover:scale-[1.02]',
    newEstimateTitle: 'text-2xl font-semibold text-gray-800 mb-2',
    newEstimateDescription: 'text-base text-gray-600',
    newEstimateIcon: 'text-5xl text-[#00c4cc]',
    subGrid: 'grid grid-cols-2 gap-6',
    subCard: 'bg-white/7 p-6 rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 cursor-pointer',
    subCardContent: 'flex items-center space-x-4',
    templateIconBg: 'bg-[#00c4cc]/4 p-3 rounded-lg',
    settingIconBg: 'bg-[#8b3dff]4 p-3 rounded-lg',
    subCardIcon: 'text-3xl text-[#00c4cc]',
    settingIcon: 'text-3xl text-[#8b3dff]',
    subCardTitle: 'text-lg font-medium text-gray-800',
    subCardDescription: 'text-base text-gray-600',
}
