export const profileStyles = {
    container: '!bg-white px-10 py-6 rounded-xl overflow-auto',
    title: 'text-2xl font-bold text-gray-800 mb-6',
    form: 'w-full',
    sectionTitle: 'text-lg font-medium text-gray-700 mb-2',
    sectionDescription: 'text-sm text-gray-500 mb-4',
    infoSection: 'py-6',
    infoItem: 'flex justify-between items-center py-3',
    infoLabel: 'text-gray-500 font-medium text-sm mb-1',
    infoValue: 'text-gray-800 font-medium text-lg h-10 flex items-center',
    bioValue: 'text-gray-800 font-medium text-lg min-h-[74px] py-2 flex-col items-start justify-center',
    valueContainer: 'flex flex-col justify-center',
    infoEditButton: 'border border-[#6366f1] text-[#6366f1] hover:text-[#4f46e5] hover:border-[#4f46e5]',
    editActions: 'flex gap-2 ml-4',
    editCancelButton: 'border border-gray-300 text-gray-600',
    editSaveButton: '!bg-[#6366f1] !text-white hover:!bg-[#4f46e5]',
    input: 'h-10 rounded-lg w-full max-w-sm',
    textArea: 'min-h-[74px] rounded-lg',
    divider: 'my-0 border-gray-200',
}
